import axios, { AxiosError } from "axios";
import Head from "next/head";
import Image from "next/image";
import { useMutation } from "react-query";
import styles from "../styles/Home.module.css";
import { PayPalScriptProvider, PayPalButtons, FUNDING } from "@paypal/react-paypal-js";
import { OnApproveData } from "@paypal/paypal-js";

export default function Home() {
  const createMutation = useMutation<{ data: any }, AxiosError, any, Response>((): any =>
    axios.post("/api/paypal/createOrder"),
  );
  const captureMutation = useMutation<string, AxiosError, any, Response>((data): any =>
    axios.post("/api/paypal/captureOrder", data),
  );
  const createPayPalOrder = async (): Promise<string> => {
    const response = await createMutation.mutateAsync({});
    return response.data.orderID;
  };

  const onApprove = async (data: OnApproveData): Promise<void> => {
    return captureMutation.mutate({ orderID: data.orderID });
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {captureMutation.data && <div>{JSON.stringify(captureMutation.data)}</div>}
        <h1>Fiat Paymaster</h1>
        <PayPalScriptProvider
          options={{
            "client-id": process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID as string,
            currency: "USD",
          }}
        >
          <PayPalButtons
            style={{
              color: "gold",
              shape: "rect",
              label: "pay",
              height: 50,
            }}
            fundingSource={FUNDING.PAYPAL}
            createOrder={createPayPalOrder}
            onApprove={onApprove}
          />
        </PayPalScriptProvider>
      </main>

      <footer className={styles.footer}>
        <a href="https://github.com/aviggiano" target="_blank" rel="noopener noreferrer">
          @aviggiano
        </a>
        <a href="https://github.com/delaaxe" target="_blank" rel="noopener noreferrer">
          @delaaxe
        </a>
        <a href="https://github.com/raigal-r" target="_blank" rel="noopener noreferrer">
          @raigal-r
        </a>
      </footer>
    </div>
  );
}

// declare global {
//   interface Window {
//     paypal: any;
//   }
// }
